import LegalPage, { LegalH2, LegalP, LegalUL } from '@/components/exam-prep/LegalPage';

export default function ExamPrepDisclaimers() {
  return (
    <LegalPage title="Disclaimers" effectiveDate="April 14, 2026">
      <LegalH2>Not affiliated with any licensing board or exam sponsor</LegalH2>
      <LegalP>
        EduCare Exam Prep Studio is an independent study aid. It is{' '}
        <strong>not affiliated with, endorsed by, sponsored by, or authorized by</strong> any of
        the following organizations:
      </LegalP>
      <LegalUL>
        <li>California Board of Behavioral Sciences (BBS)</li>
        <li>National Board for Certified Counselors (NBCC), which administers the NCMHCE</li>
        <li>Association of Social Work Boards (ASWB)</li>
        <li>California Association of Marriage and Family Therapists (CAMFT)</li>
        <li>National Association of Social Workers (NASW)</li>
        <li>American Counseling Association (ACA)</li>
        <li>Any California state agency or any other exam sponsor or professional association</li>
      </LegalUL>
      <LegalP>
        All trademarks, service marks, and exam names referenced on the Service are the property
        of their respective owners and are used only to describe the exams for which our content
        may help you prepare.
      </LegalP>

      <LegalH2>AI-generated study content</LegalH2>
      <LegalP>
        Practice questions, rationales, flashcards, clinical simulations, and study plans are
        generated by artificial intelligence. Despite our quality controls:
      </LegalP>
      <LegalUL>
        <li>AI-generated content may contain factual errors, outdated references, or omissions.</li>
        <li>Statutes, regulations, and ethics codes change; always verify current language against the primary source before relying on it.</li>
        <li>The difficulty, format, and weighting of generated questions may not perfectly match the actual exam.</li>
      </LegalUL>

      <LegalH2>Not legal, clinical, or professional advice</LegalH2>
      <LegalP>
        Content provided through the Service is for educational and study support only. It is
        not:
      </LegalP>
      <LegalUL>
        <li>Legal advice, and is not a substitute for consultation with a licensed attorney;</li>
        <li>Clinical advice, diagnosis, or treatment, and is not a substitute for clinical judgment or supervision;</li>
        <li>A regulatory interpretation by the BBS, NBCC, ASWB, or any licensing body.</li>
      </LegalUL>
      <LegalP>
        Do not rely on the Service for any decision that requires professional judgment, including
        patient care, documentation, mandated reporting, licensure applications, or disciplinary
        responses. Consult a qualified attorney, supervisor, or the relevant licensing board.
      </LegalP>

      <LegalH2>No exam outcome guarantee</LegalH2>
      <LegalP>
        EduCare makes no guarantee, warranty, or representation that using the Service will
        result in passing any exam or obtaining any license. Exam outcomes depend on many factors
        outside our control.
      </LegalP>

      <LegalH2>Verify with primary sources</LegalH2>
      <LegalP>For authoritative information, consult the primary source:</LegalP>
      <LegalUL>
        <li>California Business and Professions Code and California Code of Regulations Title 16</li>
        <li>BBS, NBCC, and ASWB official websites and candidate handbooks</li>
        <li>DSM-5-TR, published by the American Psychiatric Association</li>
        <li>The current ethics code of your professional association</li>
      </LegalUL>

      <LegalH2>Report content issues</LegalH2>
      <LegalP>
        If you spot an inaccuracy or concern with generated content, please report it to{' '}
        <a className="text-blue-700 underline hover:text-blue-800" href="mailto:support@educarecomplete.com">
          support@educarecomplete.com
        </a>{' '}
        so our team can review and correct it.
      </LegalP>
    </LegalPage>
  );
}
